import 'package:fopa_sop_apk/features/feat_auth/datas/models/user_model.dart';
import 'package:fopa_sop_apk/features/feat_category/datas/models/category_response_model.dart';
import 'package:fopa_sop_apk/features/feat_customer/datas/models/customer_response_model.dart';
import 'package:fopa_sop_apk/features/feat_product/datas/models/product_response_model.dart';
import 'package:fopa_sop_apk/features/feat_user/datas/models/user_response_model.dart';

class FakeOrder {
  static List<CustomerResponseModel> getCustomers() {
    return [
      CustomerResponseModel(
        id: '1',
        userId: 'user1',
        user: UserResponseModel(
          id: 'user1',
          email: 'jean.dupont@example.com',
          name: 'Jean Dupont',
          phone: '+237 690 123 456',
          username: 'jean.dupont',
          role: UserRole.CLIENT,
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        address: 'Douala, Cameroun',
        currentDebt: 15000.0,
        currentPackagesDebt: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      CustomerResponseModel(
        id: '2',
        userId: 'user2',
        user: UserResponseModel(
          id: 'user2',
          email: 'marie.lefevre@example.com',
          name: 'Marie Lefevre',
          phone: '+237 691 234 567',
          username: 'marie.lefevre',
          role: UserRole.CLIENT,
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        address: 'Yaoundé, Cameroun',
        currentDebt: 25000.0,
        currentPackagesDebt: 20,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      CustomerResponseModel(
        id: '3',
        userId: 'user3',
        user: UserResponseModel(
          id: 'user3',
          email: 'paul.martin@example.com',
          name: 'Paul Martin',
          phone: '+237 692 345 678',
          username: 'paul.martin',
          role: UserRole.CLIENT,
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        address: 'Bafoussam, Cameroun',
        currentDebt: 5000.0,
        currentPackagesDebt: 30,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      CustomerResponseModel(
        id: '4',
        userId: 'user4',
        user: UserResponseModel(
          id: 'user4',
          email: 'sophie.bernard@example.com',
          name: 'Sophie Bernard',
          phone: '+237 693 456 789',
          username: 'sophie.bernard',
          role: UserRole.CLIENT,
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        address: 'Garoua, Cameroun',
        currentDebt: 30000.0,
        currentPackagesDebt: 40,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      CustomerResponseModel(
        id: '5',
        userId: 'user5',
        user: UserResponseModel(
          id: 'user5',
          email: 'lucas.dubois@example.com',
          name: 'Lucas Dubois',
          phone: '+237 694 567 890',
          username: 'lucas.dubois',
          role: UserRole.CLIENT,
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        address: 'Buea, Cameroun',
        currentDebt: 10000.0,
        currentPackagesDebt: 50,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];
  }

  static List<ProductResponseModel> getProducts() {
    return [
      ProductResponseModel(
        id: '1',
        name: 'Produit A',
        categoryId: 'cat1',
        category: CategoryResponseModel(
          id: 'cat1',
          name: 'Catégorie 1',
          description: 'Description catégorie 1',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        quantity: 100,
        price: 5000.0,
        description: 'Description produit A',
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ProductResponseModel(
        id: '2',
        name: 'Produit B',
        categoryId: 'cat1',
        category: CategoryResponseModel(
          id: 'cat1',
          name: 'Catégorie 1',
          description: 'Description catégorie 1',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        quantity: 80,
        price: 3000.0,
        description: 'Description produit B',
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ProductResponseModel(
        id: '3',
        name: 'Produit C',
        categoryId: 'cat2',
        category: CategoryResponseModel(
          id: 'cat2',
          name: 'Catégorie 2',
          description: 'Description catégorie 2',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        quantity: 150,
        price: 2000.0,
        description: 'Description produit C',
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ProductResponseModel(
        id: '4',
        name: 'Produit D',
        categoryId: 'cat2',
        category: CategoryResponseModel(
          id: 'cat2',
          name: 'Catégorie 2',
          description: 'Description catégorie 2',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        quantity: 60,
        price: 7500.0,
        description: 'Description produit D',
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      ProductResponseModel(
        id: '5',
        name: 'Produit E',
        categoryId: 'cat3',
        category: CategoryResponseModel(
          id: 'cat3',
          name: 'Catégorie 3',
          description: 'Description catégorie 3',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
        quantity: 200,
        price: 1500.0,
        description: 'Description produit E',
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];
  }
}
