import 'package:flutter/material.dart';

Map<String, Color> colorsLetter = {
  'A': Colors.red,
  'B': Colors.blue,
  'C': Colors.green,
  'D': Colors.yellow,
  'E': Colors.purple,
  'F': Colors.orange,
  'G': Colors.brown,
  'H': Colors.grey,
  'I': Colors.pink,
  'J': Colors.teal,
  'K': Colors.indigo,
  'L': Colors.lime,
  'M': Colors.cyan,
  'N': Colors.deepPurple,
  'O': Colors.deepOrange,
  'P': Colors.deepPurpleAccent,
  'Q': Colors.deepOrangeAccent,
  'R': Colors.deepPurpleAccent,
  'S': Colors.deepOrangeAccent,
  'T': Colors.deepPurpleAccent,
  'U': Colors.deepOrangeAccent,
  'V': Colors.deepPurpleAccent,
  'W': Colors.deepOrangeAccent,
  'X': Colors.deepPurpleAccent,
  'Y': Colors.deepOrangeAccent,
  'Z': Colors.deepPurpleAccent,
};
