name: fopa-sop
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fopa-sop
    ports:
      - "8085:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:16-alpine
    container_name: fopa-sop-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

networks:
  network:
    driver: bridge
